/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\helicopter.gltf 
Author: disa.svennberg (https://sketchfab.com/disa.svennberg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/helikopter-860e7732bcd84e7cb81cc8031fce568c
Title: Helikopter
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Helicopter(props) {
  const { nodes, materials } = useGLTF('/helicopter.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/helicopter.gltf')
